### ISSUE TITLE
Feature: Allow defining description for each event ID

### ISSUE THREAD

**Issue by ghost** [Berrysoft/winlog#1]
In the current state, events logged will have the standard message below explaining that Windows cannot find a description for the event ID, cluttering the log itself.

```
The description for Event ID 3 from source RegisteredName cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
```

**Comment by Berrysoft** [comment]
You need to call `register` with Administer permission to register the message types of current executable.

**Comment by ghost** [comment]
I did so, yes. Would that need to be done again for every build? Is that the issue I'm having?

**Comment by Berrysoft** [comment]
`register` registers the `current_exe` to the registry, so that the event manager could find the registered binary and look up the message types. If the registered exe is moved, or `unregister` is called, the event manager could not find the binary and will complain about the message type.

I don't understand what you mean for "every build". Would you share your code about how you use this crate?

**Comment by ghost** [comment]
I was curious if any change in the exe produced a new GUID/fingerprint and if that was how the calls worked. I see now what the issue was, thanks.
